exports['fenwick'] = ['fenwick:1','fenwick:2','fenwick:3','fenwick:4','fenwick:5',]
exports['fenwick:1'] = ["fenwick:1:Argo.Tea.and.Reading.Area", "fenwick:1:Atrium", "fenwick:1:A", "fenwick:1:B", "fenwick:1:C", "fenwick:1:D"]
exports['fenwick:2'] = ['fenwick:2:Research.Commons','fenwick:2:A','fenwick:2:B','fenwick:2:C','fenwick:2:D', 'fenwick:2:E', 'fenwick:2:G', 'fenwick:2:North.Reading.Room']
exports['fenwick:3'] = ['fenwick:3:A','fenwick:3:B','fenwick:3:C','fenwick:3:D','fenwick:3:E','fenwick:3:F','fenwick:3:G','fenwick:3:Study.Zone.East','fenwick:3:Study.Zone.South']
exports['fenwick:4'] = ['fenwick:4:A','fenwick:4:B','fenwick:4:C','fenwick:4:D','fenwick:4:E','fenwick:4:F','fenwick:4:Study.Zone.East','fenwick:4:Study.Zone.South',]
exports['fenwick:5'] = ['fenwick:5:A','fenwick:5:B','fenwick:5:C','fenwick:5:D','fenwick:5:E','fenwick:5:Graduate.Student.Research.Zone.Southeast','fenwick:5:Graduate.Student.Research.Zone.East.Northeast']
exports['buildings'] = ['fenwick']